name: Copilot Session Setup

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4          
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
        
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/build.properties') }}
          restore-keys: ${{ runner.os }}-sbt-
      
      - name: Setup SBT
        run: |
          curl -fL https://github.com/sbt/sbt/releases/download/v1.9.6/sbt-1.9.6.tgz | tar xz
          echo "$PWD/sbt/bin" >> $GITHUB_PATH          
        
      - name: Verify Environment
        run: |    
          java -version
          sbt -version
          echo "Copilot development environment set up successfully."
      
